// ============================================================
// Generated by HTML → Flutter Generator
// Drop this file into flutter_html_form/lib/main.dart
// then run: flutter run
// ============================================================
import 'package:flutter/material.dart';

void main() => runApp(const _PreviewApp());

class _PreviewApp extends StatefulWidget {
  const _PreviewApp({super.key});
  @override
  State<_PreviewApp> createState() => _PreviewAppState();
}

class _PreviewAppState extends State<_PreviewApp> {
  final _transformationController = TransformationController();
  double _currentScale = 1.0;


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blueGrey,
          foregroundColor: Colors.white,
          title: Text('Preview (${(_currentScale * 100).toInt()}%)'),
          actions: [
            IconButton(icon: const Icon(Icons.zoom_out), onPressed: () => _zoom(-0.2)),
            IconButton(icon: const Icon(Icons.zoom_in),  onPressed: () => _zoom(0.2)),
            IconButton(icon: const Icon(Icons.refresh),  onPressed: _resetZoom),
          ],
        ),
        body: LayoutBuilder(
          builder: (ctx, outerConstraints) => InteractiveViewer(
          transformationController: _transformationController,
          minScale: 0.5,
          maxScale: 5.0,
          constrained: false,
          boundaryMargin: const EdgeInsets.all(double.infinity),
          onInteractionUpdate: (details) => setState(() {
            _currentScale = _transformationController.value.getMaxScaleOnAxis();
          }),
          child: SizedBox(
            width: outerConstraints.maxWidth,
            child: Container(
              color: Colors.white,
              padding: const EdgeInsets.all(16),
              child: UnconstrainedBox(
  alignment: Alignment.topLeft,
  child: Container(
  margin: EdgeInsets.fromLTRB(20, 20, 20, 20),
  padding: EdgeInsets.fromLTRB(8, 8, 8, 8),
  decoration: BoxDecoration(border: Border(top: BorderSide(color: Colors.black, width: 1), right: BorderSide(color: Colors.black, width: 1), bottom: BorderSide(color: Colors.black, width: 1), left: BorderSide(color: Colors.black, width: 1))),
  child: LayoutBuilder(
  builder: (context, constraints) {
    final availableWidth = 280.0.clamp(0.0, constraints.maxWidth);

    final fixedTotal = 276.0;
    final flexSpace = availableWidth.isInfinite ? 0.0 : (availableWidth - fixedTotal).clamp(0.0, double.infinity);
    final flexUnit = flexSpace / 0.001000;
    final colWidths = <double>[
      15.0,
      94.0,
      65.0,
      51.0,
      51.0,
    ];

    final rowHeights = <double>[50.0, 41.0, 20.0, 37.0, 22.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 33.0, 22.0, 23.0, 38.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 38.0];

    final cs = <double>[0.0];
    for (final w in colWidths) { cs.add(cs.last + w); }
    final rs = <double>[0.0];
    for (final h in rowHeights) { rs.add(rs.last + h); }

    final totalWidth = cs.last;
    final totalHeight = rs.last;

    Positioned cell(int c, int r, int ce, int re,
        {Border? border, Color? bg, EdgeInsets pad = EdgeInsets.zero,
        Alignment align = Alignment.centerLeft, required Widget child}) =>
      Positioned(left: cs[c], top: rs[r], width: cs[ce] - cs[c], height: rs[re] - rs[r],
          child: Container(
              decoration: (border != null || bg != null) ? BoxDecoration(border: border, color: bg) : null,
              padding: pad, alignment: align, child: child));

    final matrixData = <List<int>>[
      <int>[0, 0, 0, 0, 0],
      <int>[1, 1, 1, 1, 1],
      <int>[2, 2, 2, 2, 2],
      <int>[3, 3, 3, 4, 4],
      <int>[5, 5, 5, 5, 5],
      <int>[6, 6, 6, 6, 7],
      <int>[8, 9, 9, 9, 10],
      <int>[11, 12, 12, 12, 13],
      <int>[14, 14, 14, 14, 15],
      <int>[16, 16, 16, 16, 17],
      <int>[18, 18, 18, 18, 19],
      <int>[20, 21, 21, 21, 22],
      <int>[23, 24, 24, 24, 25],
      <int>[26, 26, 26, 26, 27],
      <int>[28, 28, 28, 29, 29],
      <int>[30, 30, 30, 31, 31],
      <int>[32, 32, 32, 32, 32],
      <int>[33, 33, 34, 35, 36],
      <int>[37, 37, 38, 39, 40],
      <int>[41, 42, 43, 44, 45],
      <int>[46, 46, 47, 48, 49],
      <int>[50, 50, 51, 52, 53],
      <int>[54, 54, 54, 55, 56],
      <int>[57, 58, 58, 59, 60],
      <int>[61, 61, 61, 61, 61],
    ];

    return SizedBox(
      width: totalWidth,
      height: totalHeight,
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          cell(0, 0, 5, 1, border: _bBottom(10), pad: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 4.0), child: _t('Nutrition Facts', sz: 24.0, bold: true, ff: 'Arial')),
          cell(0, 1, 5, 2, border: _bBottom(), pad: EdgeInsets.symmetric(vertical: 2.0, horizontal: 0.0), child: _rt([(' Serving Size 1/2 cup (about 82g)', false), ('\n', false), (' Serving Per Container 8 ', false)], sz: 12.0, ff: 'Arial')),
          cell(0, 2, 5, 3, pad: EdgeInsets.fromLTRB(0.0, 4.0, 0.0, 0.0), child: _t('Amount Per Serving', sz: 10.0, bold: true, ff: 'Arial')),
          cell(0, 3, 3, 4, border: _bTop(), child: _rt([('Calories', true), (' 200', false)], sz: 14.0, ff: 'Arial')),
          cell(3, 3, 5, 4, border: _bTop(), align: Alignment.centerRight, child: _t('Calories from Fat 130', sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 4, 5, 5, border: _bTop(5), pad: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 2.0), align: Alignment.centerRight, child: _t('% Daily Value*', sz: 10.0, bold: true, ff: 'Arial', align: TextAlign.right)),
          cell(0, 5, 4, 6, border: _bTop(), child: _rt([('Total Fat', true), (' 14g', false)], sz: 12.0, ff: 'Arial')),
          cell(4, 5, 5, 6, border: _bTop(), align: Alignment.centerRight, child: _rt([('22%', true)], sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 6, 1, 7, child: const SizedBox.shrink()),
          cell(1, 6, 4, 7, border: _bTop(), child: _t('Saturated Fat 9g', sz: 12.0, ff: 'Arial')),
          cell(4, 6, 5, 7, border: _bTop(), align: Alignment.centerRight, child: _rt([('22%', true)], sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 7, 1, 8, child: const SizedBox.shrink()),
          cell(1, 7, 4, 8, border: _bTop(), child: _t('Trans Fat 0g', sz: 12.0, ff: 'Arial')),
          cell(4, 7, 5, 8, border: _bTop(), child: const SizedBox.shrink()),
          cell(0, 8, 4, 9, border: _bTop(), child: _rt([('Cholesterol', true), (' 55mg', false)], sz: 12.0, ff: 'Arial')),
          cell(4, 8, 5, 9, border: _bTop(), align: Alignment.centerRight, child: _rt([('18%', true)], sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 9, 4, 10, border: _bTop(), child: _rt([('Sodium', true), (' 40mg', false)], sz: 12.0, ff: 'Arial')),
          cell(4, 9, 5, 10, border: _bTop(), align: Alignment.centerRight, child: _rt([('2%', true)], sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 10, 4, 11, border: _bTop(), child: _rt([('Total Carbohydrate', true), (' 17g', false)], sz: 12.0, ff: 'Arial')),
          cell(4, 10, 5, 11, border: _bTop(), align: Alignment.centerRight, child: _rt([('6%', true)], sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 11, 1, 12, child: const SizedBox.shrink()),
          cell(1, 11, 4, 12, border: _bTop(), child: _t('Dietary Fiber 1g', sz: 12.0, ff: 'Arial')),
          cell(4, 11, 5, 12, border: _bTop(), align: Alignment.centerRight, child: _rt([('4%', true)], sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 12, 1, 13, child: const SizedBox.shrink()),
          cell(1, 12, 4, 13, border: _bTop(), child: _t('Sugars 14g', sz: 12.0, ff: 'Arial')),
          cell(4, 12, 5, 13, border: _bTop(), child: const SizedBox.shrink()),
          cell(0, 13, 4, 14, border: _bTopBottom(1, 10), pad: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 4.0), child: _rt([('Protein', true), (' 3g', false)], sz: 12.0, ff: 'Arial')),
          cell(4, 13, 5, 14, border: _bTopBottom(1, 10), child: const SizedBox.shrink()),
          cell(0, 14, 3, 15, pad: EdgeInsets.fromLTRB(0.0, 4.0, 0.0, 0.0), child: _t('Vitamin A 10%', sz: 12.0, ff: 'Arial')),
          cell(3, 14, 5, 15, pad: EdgeInsets.fromLTRB(0.0, 4.0, 0.0, 0.0), align: Alignment.centerRight, child: _t('Vitamin C 0%', sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 15, 3, 16, border: _bBottom(), pad: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 4.0), child: _t('Calcium 10%', sz: 12.0, ff: 'Arial')),
          cell(3, 15, 5, 16, border: _bBottom(), pad: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 4.0), align: Alignment.centerRight, child: _t('Iron 6%', sz: 12.0, ff: 'Arial', align: TextAlign.right)),
          cell(0, 16, 5, 17, pad: EdgeInsets.symmetric(vertical: 4.0, horizontal: 0.0), child: _t('* Percent Daily Values are based on a 2,000 calorie diet.', sz: 10.0, ff: 'Arial')),
          cell(0, 17, 2, 18, child: const SizedBox.shrink()),
          cell(2, 17, 3, 18, border: _bBottom(), child: _t('Calories:', sz: 10.0, ff: 'Arial')),
          cell(3, 17, 4, 18, border: _bBottom(), child: _t('2,000', sz: 10.0, ff: 'Arial')),
          cell(4, 17, 5, 18, border: _bBottom(), child: _t('2,500', sz: 10.0, ff: 'Arial')),
          cell(0, 18, 2, 19, child: _rt([('Total Fat', true)], sz: 10.0, ff: 'Arial')),
          cell(2, 18, 3, 19, child: _t('Less than', sz: 10.0, ff: 'Arial')),
          cell(3, 18, 4, 19, child: _t('65g', sz: 10.0, ff: 'Arial')),
          cell(4, 18, 5, 19, child: _t('80g', sz: 10.0, ff: 'Arial')),
          cell(0, 19, 1, 20, child: const SizedBox.shrink()),
          cell(1, 19, 2, 20, child: _t('Saturated Fat', sz: 10.0, ff: 'Arial')),
          cell(2, 19, 3, 20, child: _t('Less than', sz: 10.0, ff: 'Arial')),
          cell(3, 19, 4, 20, child: _t('20g', sz: 10.0, ff: 'Arial')),
          cell(4, 19, 5, 20, child: _t('25g', sz: 10.0, ff: 'Arial')),
          cell(0, 20, 2, 21, child: _rt([('Cholesterol', true)], sz: 10.0, ff: 'Arial')),
          cell(2, 20, 3, 21, child: _t('Less than', sz: 10.0, ff: 'Arial')),
          cell(3, 20, 4, 21, child: _t('300mg', sz: 10.0, ff: 'Arial')),
          cell(4, 20, 5, 21, child: _t('300mg', sz: 10.0, ff: 'Arial')),
          cell(0, 21, 2, 22, child: _rt([('Sodium', true)], sz: 10.0, ff: 'Arial')),
          cell(2, 21, 3, 22, child: _t('Less than', sz: 10.0, ff: 'Arial')),
          cell(3, 21, 4, 22, child: _t('2,400mg', sz: 10.0, ff: 'Arial')),
          cell(4, 21, 5, 22, child: _t('2,400mg', sz: 10.0, ff: 'Arial')),
          cell(0, 22, 3, 23, child: _rt([('Total Carbohydrate', true)], sz: 10.0, ff: 'Arial')),
          cell(3, 22, 4, 23, child: _t('300g', sz: 10.0, ff: 'Arial')),
          cell(4, 22, 5, 23, child: _t('375g', sz: 10.0, ff: 'Arial')),
          cell(0, 23, 1, 24, child: const SizedBox.shrink()),
          cell(1, 23, 3, 24, child: _t('Dietary Fiber', sz: 10.0, ff: 'Arial')),
          cell(3, 23, 4, 24, child: _t('25g', sz: 10.0, ff: 'Arial')),
          cell(4, 23, 5, 24, child: _t('30g', sz: 10.0, ff: 'Arial')),
          cell(0, 24, 5, 25, pad: EdgeInsets.fromLTRB(0.0, 8.0, 0.0, 0.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  _rt([(' Calories per gram:', false)], sz: 10.0, ff: 'Arial'),
                  Text('Fat 9 • Carbohydrate 4 • Protein 4', style: TextStyle(fontFamily: 'Arial', fontSize: 10.0), textAlign: TextAlign.center),
                ],
              )),
          Positioned.fill(
            child: CustomPaint(
              painter: _TableGridPainter(
                colStarts: cs,
                rowStarts: rs,
                borderColor: Colors.black,
                borderWidth: 0.0,
                matrixData: matrixData,
                numRows: 25,
                numCols: 5,
              ),
            ),
          ),
        ],
      ),
    );
  },
),
),
),
            ),
          ),
        ),
        ),
      ),
    );
  }

  void _zoom(double delta) {
    setState(() {
      _currentScale = (_currentScale + delta).clamp(0.5, 5.0);
      _transformationController.value = Matrix4.diagonal3Values(_currentScale, _currentScale, 1.0);
    });
  }

  void _resetZoom() {
    setState(() {
      _currentScale = 1.0;
      _transformationController.value = Matrix4.identity();
    });
  }
}

// ============ HELPER CLASSES ============
// ── Text helpers ──────────────────────────────────────────────────────────────

Widget _t(String s, {double sz = 16, bool bold = false, Color? color, String ff = 'Browallia New', TextAlign? align}) =>
    Text(s, style: TextStyle(fontFamily: ff, fontSize: sz, fontWeight: bold ? FontWeight.bold : FontWeight.normal, color: color), softWrap: true, overflow: TextOverflow.clip, textAlign: align);

Widget _rt(List<(String, bool)> spans, {double sz = 16, String ff = 'Browallia New', TextAlign align = TextAlign.start}) =>
    RichText(softWrap: true, overflow: TextOverflow.clip, textAlign: align,
        text: TextSpan(style: TextStyle(fontFamily: ff, fontSize: sz),
            children: [for (final (t, b) in spans) TextSpan(text: t, style: b ? const TextStyle(fontWeight: FontWeight.bold) : null)]));

// ── Border helpers ────────────────────────────────────────────────────────────

const _bk = Colors.black;
Border _bTop([double w = 1])    => Border(top:    BorderSide(color: _bk, width: w));
Border _bBottom([double w = 1]) => Border(bottom: BorderSide(color: _bk, width: w));
Border _bTopBottom(double t, double b) => Border(top: BorderSide(color: _bk, width: t), bottom: BorderSide(color: _bk, width: b));

class _TableGridPainter extends CustomPainter {
  final List<double> colStarts;
  final List<double> rowStarts;
  final Color borderColor;
  final double borderWidth;
  final List<List<int>> matrixData;
  final int numRows;
  final int numCols;

  const _TableGridPainter({
    required this.colStarts,
    required this.rowStarts,
    required this.borderColor,
    required this.borderWidth,
    required this.matrixData,
    required this.numRows,
    required this.numCols,
  });

  @override
  void paint(Canvas canvas, Size size) {
    if (borderWidth == 0) return;
    final paint = Paint()
      ..color = borderColor
      ..strokeWidth = borderWidth
      ..style = PaintingStyle.stroke;
    for (int r = 0; r < numRows; r++) {
      for (int c = 0; c < numCols; c++) {
        if (c >= colStarts.length - 1 || r >= rowStarts.length - 1) continue;
        final idx = (r < matrixData.length && c < matrixData[r].length)
            ? matrixData[r][c]
            : -1;
        if (idx < 0) continue;
        final sameAsLeft  = c > 0 && matrixData[r][c - 1] == idx;
        final sameAsAbove = r > 0 && matrixData[r - 1][c] == idx;
        if (sameAsLeft || sameAsAbove) continue;
        int endC = c + 1;
        while (endC < numCols && endC < matrixData[r].length && matrixData[r][endC] == idx) endC++;
        int endR = r + 1;
        while (endR < numRows && endR < matrixData.length && matrixData[endR][c] == idx) endR++;
        final right  = endC < colStarts.length ? colStarts[endC] : colStarts.last;
        final bottom = endR < rowStarts.length ? rowStarts[endR] : rowStarts.last;
        canvas.drawRect(Rect.fromLTRB(colStarts[c], rowStarts[r], right, bottom), paint);
      }
    }
  }

  @override
  bool shouldRepaint(_TableGridPainter old) =>
      old.borderColor != borderColor || old.borderWidth != borderWidth;
}