// ============================================================
// Generated by HTML → Flutter Generator
// Drop this file into flutter_html_form/lib/main.dart
// then run: flutter run
// ============================================================
import 'package:flutter/material.dart';

void main() => runApp(const _PreviewApp());

class _PreviewApp extends StatefulWidget {
  const _PreviewApp({super.key});
  @override
  State<_PreviewApp> createState() => _PreviewAppState();
}

class _PreviewAppState extends State<_PreviewApp> {
  final _transformationController = TransformationController();
  double _currentScale = 1.0;


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.blueGrey,
          foregroundColor: Colors.white,
          title: Text('Preview (${(_currentScale * 100).toInt()}%)'),
          actions: [
            IconButton(icon: const Icon(Icons.zoom_out), onPressed: () => _zoom(-0.2)),
            IconButton(icon: const Icon(Icons.zoom_in),  onPressed: () => _zoom(0.2)),
            IconButton(icon: const Icon(Icons.refresh),  onPressed: _resetZoom),
          ],
        ),
        body: LayoutBuilder(
          builder: (ctx, outerConstraints) => InteractiveViewer(
          transformationController: _transformationController,
          minScale: 0.5,
          maxScale: 5.0,
          constrained: false,
          boundaryMargin: const EdgeInsets.all(double.infinity),
          onInteractionUpdate: (details) => setState(() {
            _currentScale = _transformationController.value.getMaxScaleOnAxis();
          }),
          child: SizedBox(
            width: outerConstraints.maxWidth,
            child: Container(
              color: Colors.white,
              padding: const EdgeInsets.all(16),
              child: UnconstrainedBox(
                alignment: Alignment.topLeft,
                child: Container(
                padding: const EdgeInsets.all(16),
                margin: const EdgeInsets.all(0),
                width: 800,
                decoration: BoxDecoration(color: Color(0xFFF9FAFC), border: Border(top: BorderSide(color: Color(0xFFEEEEEE), width: 1), right: BorderSide(color: Color(0xFFEEEEEE), width: 1), bottom: BorderSide(color: Color(0xFFEEEEEE), width: 1), left: BorderSide(color: Color(0xFFEEEEEE), width: 1))),
                child: LayoutBuilder(
  builder: (context, constraints) {
    final availableWidth = constraints.maxWidth;

    final fixedTotal = 0.0;
    final flexSpace = availableWidth.isInfinite ? 0.0 : (availableWidth - fixedTotal).clamp(0.0, double.infinity);
    final flexUnit = flexSpace / 1.000000;
    final colWidths = <double>[
      flexUnit,
    ];

    final rowHeights = <double>[81.0, 738.0, 70.0];

    final cs = <double>[0.0];
    for (final w in colWidths) { cs.add(cs.last + w); }
    final rs = <double>[0.0];
    for (final h in rowHeights) { rs.add(rs.last + h); }

    final totalWidth = cs.last;
    final totalHeight = rs.last;

    Positioned cell(int c, int r, int ce, int re,
        {Border? border, Color? bg, EdgeInsets pad = EdgeInsets.zero,
        Alignment align = Alignment.centerLeft, required Widget child}) =>
      Positioned(left: cs[c], top: rs[r], width: cs[ce] - cs[c], height: rs[re] - rs[r],
          child: Container(
              decoration: (border != null || bg != null) ? BoxDecoration(border: border, color: bg) : null,
              padding: pad, alignment: align, child: child));

    final matrixData = <List<int>>[
      <int>[0],
      <int>[1],
      <int>[2],
    ];

    return SizedBox(
      width: totalWidth,
      height: totalHeight,
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          cell(0, 0, 1, 1, bg: Colors.grey.shade200, pad: EdgeInsets.fromLTRB(16.0, 0.0, 16.0, 18.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Alvish Baldha (Courier)', style: TextStyle(fontFamily: 'Browallia New', fontSize: 18.0, fontWeight: FontWeight.bold, color: Color(0xFF1A1C21))),
                  Text('hello@email.com', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.bold)),
                  Text('+44 7766002333', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.bold)),
                ],
              )),
          cell(0, 1, 1, 2, pad: EdgeInsets.all(4.0), child: Container(
  padding: EdgeInsets.fromLTRB(16, 20, 16, 20),
  decoration: BoxDecoration(border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1), right: BorderSide(color: Color(0xFFD7DAE0), width: 1), bottom: BorderSide(color: Color(0xFFD7DAE0), width: 1), left: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
  child: LayoutBuilder(
  builder: (context, constraints) {
    final availableWidth = constraints.maxWidth;

    final fixedTotal = 0.0;
    final flexSpace = availableWidth.isInfinite ? 0.0 : (availableWidth - fixedTotal).clamp(0.0, double.infinity);
    final flexUnit = flexSpace / 1.650000;
    final colWidths = <double>[
      flexUnit * 0.300000,
      flexUnit * 0.350000,
      flexUnit,
    ];

    final rowHeights = <double>[215.0, 69.0, 446.0];

    final cs = <double>[0.0];
    for (final w in colWidths) { cs.add(cs.last + w); }
    final rs = <double>[0.0];
    for (final h in rowHeights) { rs.add(rs.last + h); }

    final totalWidth = cs.last;
    final totalHeight = rs.last;

    Positioned cell(int c, int r, int ce, int re,
        {Border? border, Color? bg, EdgeInsets pad = EdgeInsets.zero,
        Alignment align = Alignment.centerLeft, required Widget child}) =>
      Positioned(left: cs[c], top: rs[r], width: cs[ce] - cs[c], height: rs[re] - rs[r],
          child: Container(
              decoration: (border != null || bg != null) ? BoxDecoration(border: border, color: bg) : null,
              padding: pad, alignment: align, child: child));

    final matrixData = <List<int>>[
      <int>[0, 1, 2],
      <int>[3, 4, 5],
      <int>[6, 6, 6],
    ];

    return SizedBox(
      width: totalWidth,
      height: totalHeight,
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          cell(0, 0, 1, 1, pad: EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 35.0), align: Alignment.topLeft, child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Client Name', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21))),
                  Text('Business address City, Country', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                  Text('email@company.com', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                ],
              )),
          cell(1, 0, 2, 1, pad: EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 35.0), align: Alignment.topLeft, child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Pick-up', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21))),
                  Text('1 Hight street, London, E1 7QL Uk', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                  Text('Drop-off', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21))),
                  Text('1 Hight street, London, E1 7QL Uk', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                ],
              )),
          cell(2, 0, 3, 1, pad: EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 35.0), align: Alignment.topLeft, child: LayoutBuilder(
  builder: (context, constraints) {
    final availableWidth = constraints.maxWidth;

    final fixedTotal = 0.0;
    final flexSpace = availableWidth.isInfinite ? 0.0 : (availableWidth - fixedTotal).clamp(0.0, double.infinity);
    final flexUnit = flexSpace / 2.000000;
    final colWidths = <double>[
      flexUnit,
      flexUnit,
    ];

    final rowHeights = <double>[26.0, 26.0, 26.0, 26.0, 26.0];

    final cs = <double>[0.0];
    for (final w in colWidths) { cs.add(cs.last + w); }
    final rs = <double>[0.0];
    for (final h in rowHeights) { rs.add(rs.last + h); }

    final totalWidth = cs.last;
    final totalHeight = rs.last;

    Positioned cell(int c, int r, int ce, int re,
        {Border? border, Color? bg, EdgeInsets pad = EdgeInsets.zero,
        Alignment align = Alignment.centerLeft, required Widget child}) =>
      Positioned(left: cs[c], top: rs[r], width: cs[ce] - cs[c], height: rs[re] - rs[r],
          child: Container(
              decoration: (border != null || bg != null) ? BoxDecoration(border: border, color: bg) : null,
              padding: pad, alignment: align, child: child));

    final matrixData = <List<int>>[
      <int>[0, 1],
      <int>[2, 3],
      <int>[4, 5],
      <int>[6, 7],
      <int>[8, 9],
    ];

    return SizedBox(
      width: totalWidth,
      height: totalHeight,
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          cell(0, 0, 1, 1, pad: EdgeInsets.all(4.0), child: _t('Job ID', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 0, 2, 1, pad: EdgeInsets.all(4.0), align: Alignment.centerRight, child: _t('123567', sz: 12.0, align: TextAlign.right)),
          cell(0, 1, 1, 2, pad: EdgeInsets.all(4.0), child: _t('Job date', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 1, 2, 2, pad: EdgeInsets.all(4.0), align: Alignment.centerRight, child: _t('14/12/2020', sz: 12.0, align: TextAlign.right)),
          cell(0, 2, 1, 3, pad: EdgeInsets.all(4.0), child: _t('Distance', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 2, 2, 3, pad: EdgeInsets.all(4.0), align: Alignment.centerRight, child: _t('1.568 miles', sz: 12.0, align: TextAlign.right)),
          cell(0, 3, 1, 4, pad: EdgeInsets.all(4.0), child: _t('Pick-up time', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 3, 2, 4, pad: EdgeInsets.all(4.0), align: Alignment.centerRight, child: _t('19:58', sz: 12.0, align: TextAlign.right)),
          cell(0, 4, 1, 5, pad: EdgeInsets.all(4.0), child: _t('Time delivered', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 4, 2, 5, pad: EdgeInsets.all(4.0), align: Alignment.centerRight, child: _t('20:58', sz: 12.0, align: TextAlign.right)),
          Positioned.fill(
            child: CustomPaint(
              painter: _TableGridPainter(
                colStarts: cs,
                rowStarts: rs,
                borderColor: Colors.black,
                borderWidth: 0.0,
                matrixData: matrixData,
                numRows: 5,
                numCols: 2,
              ),
            ),
          ),
        ],
      ),
    );
  },
)),
          cell(0, 1, 1, 2, pad: EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 13.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Service', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                  Text('Delivery Service', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21))),
                ],
              )),
          cell(1, 1, 2, 2, pad: EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 13.0), align: Alignment.center, child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Invoice number', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470)), textAlign: TextAlign.center),
                  Text('#AB2324-01', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)), textAlign: TextAlign.center),
                ],
              )),
          cell(2, 1, 3, 2, pad: EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 13.0), align: Alignment.centerRight, child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Invoice date', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470)), textAlign: TextAlign.right),
                  Text('01 Aug, 2023', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)), textAlign: TextAlign.right),
                ],
              )),
          cell(0, 2, 3, 3, pad: EdgeInsets.all(20.0), child: LayoutBuilder(
  builder: (context, constraints) {
    final availableWidth = constraints.maxWidth;

    final fixedTotal = 260.0;
    final flexSpace = availableWidth.isInfinite ? 0.0 : (availableWidth - fixedTotal).clamp(0.0, double.infinity);
    final flexUnit = flexSpace / 1.000000;
    final colWidths = <double>[
      flexUnit,
      40.0,
      100.0,
      120.0,
    ];

    final rowHeights = <double>[36.0, 60.0, 60.0, 164.0, 44.0];

    final cs = <double>[0.0];
    for (final w in colWidths) { cs.add(cs.last + w); }
    final rs = <double>[0.0];
    for (final h in rowHeights) { rs.add(rs.last + h); }

    final totalWidth = cs.last;
    final totalHeight = rs.last;

    Positioned cell(int c, int r, int ce, int re,
        {Border? border, Color? bg, EdgeInsets pad = EdgeInsets.zero,
        Alignment align = Alignment.centerLeft, required Widget child}) =>
      Positioned(left: cs[c], top: rs[r], width: cs[ce] - cs[c], height: rs[re] - rs[r],
          child: Container(
              decoration: (border != null || bg != null) ? BoxDecoration(border: border, color: bg) : null,
              padding: pad, alignment: align, child: child));

    final matrixData = <List<int>>[
      <int>[0, 1, 2, 3],
      <int>[4, 5, 6, 7],
      <int>[8, 9, 10, 11],
      <int>[12, 13, 13, 13],
      <int>[14, -1, -1, -1],
    ];

    return SizedBox(
      width: totalWidth,
      height: totalHeight,
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          Positioned(left: cs[0], top: rs[0], width: cs[1] - cs[0], height: rs[1] - rs[0], child: Container(
              decoration: BoxDecoration(color: Colors.grey.shade200, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1), bottom: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.symmetric(vertical: 8.0, horizontal: 0.0), alignment: Alignment.centerLeft, child: _t('Item Detail', sz: 12.0, bold: true))),
          Positioned(left: cs[1], top: rs[0], width: cs[2] - cs[1], height: rs[1] - rs[0], child: Container(
              decoration: BoxDecoration(color: Colors.grey.shade200, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1), bottom: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.symmetric(vertical: 8.0, horizontal: 0.0), alignment: Alignment.centerLeft, child: _t('Qty', sz: 12.0, bold: true))),
          Positioned(left: cs[2], top: rs[0], width: cs[3] - cs[2], height: rs[1] - rs[0], child: Container(
              decoration: BoxDecoration(color: Colors.grey.shade200, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1), bottom: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.symmetric(vertical: 8.0, horizontal: 0.0), alignment: Alignment.centerRight, child: _t('Rate', sz: 12.0, bold: true, align: TextAlign.right))),
          Positioned(left: cs[3], top: rs[0], width: cs[4] - cs[3], height: rs[1] - rs[0], child: Container(
              decoration: BoxDecoration(color: Colors.grey.shade200, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1), bottom: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.symmetric(vertical: 8.0, horizontal: 0.0), alignment: Alignment.centerRight, child: _t('Amount', sz: 12.0, bold: true, align: TextAlign.right))),
          cell(0, 1, 1, 2, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Drops', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21))),
                  Text('On-demand delivery', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                ],
              )),
          cell(1, 1, 2, 2, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), child: Text('1', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)))),
          cell(2, 1, 3, 2, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), align: Alignment.centerRight, child: Text('£5.00', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)), textAlign: TextAlign.right)),
          cell(3, 1, 4, 2, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), align: Alignment.centerRight, child: Text('£5.00', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)), textAlign: TextAlign.right)),
          cell(0, 2, 1, 3, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('Hours', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21))),
                  Text('Shift delivery service', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF5E6470))),
                ],
              )),
          cell(1, 2, 2, 3, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), child: Text('0', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)))),
          cell(2, 2, 3, 3, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), align: Alignment.centerRight, child: Text('£0.00', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)), textAlign: TextAlign.right)),
          cell(3, 2, 4, 3, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 4.0), align: Alignment.centerRight, child: Text('£0.00', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, fontWeight: FontWeight.w700, color: Color(0xFF1A1C21)), textAlign: TextAlign.right)),
          Positioned(left: cs[0], top: rs[3], width: cs[1] - cs[0], height: rs[4] - rs[3], child: Container(
              decoration: BoxDecoration(color: Colors.transparent, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.symmetric(vertical: 12.0, horizontal: 0.0), alignment: Alignment.centerLeft, child: const SizedBox.shrink())),
          Positioned(left: cs[1], top: rs[3], width: cs[4] - cs[1], height: rs[4] - rs[3], child: Container(
              decoration: BoxDecoration(color: Colors.transparent, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.all(4.0), alignment: Alignment.centerLeft, child: LayoutBuilder(
  builder: (context, constraints) {
    final availableWidth = constraints.maxWidth;

    final fixedTotal = 0.0;
    final flexSpace = availableWidth.isInfinite ? 0.0 : (availableWidth - fixedTotal).clamp(0.0, double.infinity);
    final flexUnit = flexSpace / 2.000000;
    final colWidths = <double>[
      flexUnit,
      flexUnit,
    ];

    final rowHeights = <double>[34.0, 42.0, 61.0];

    final cs = <double>[0.0];
    for (final w in colWidths) { cs.add(cs.last + w); }
    final rs = <double>[0.0];
    for (final h in rowHeights) { rs.add(rs.last + h); }

    final totalWidth = cs.last;
    final totalHeight = rs.last;

    Positioned cell(int c, int r, int ce, int re,
        {Border? border, Color? bg, EdgeInsets pad = EdgeInsets.zero,
        Alignment align = Alignment.centerLeft, required Widget child}) =>
      Positioned(left: cs[c], top: rs[r], width: cs[ce] - cs[c], height: rs[re] - rs[r],
          child: Container(
              decoration: (border != null || bg != null) ? BoxDecoration(border: border, color: bg) : null,
              padding: pad, alignment: align, child: child));

    final matrixData = <List<int>>[
      <int>[0, 1],
      <int>[2, 3],
      <int>[4, 5],
    ];

    return SizedBox(
      width: totalWidth,
      height: totalHeight,
      child: Stack(
        clipBehavior: Clip.hardEdge,
        children: [
          cell(0, 0, 1, 1, pad: EdgeInsets.fromLTRB(4.0, 12.0, 4.0, 4.0), child: _t('Subtotal', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 0, 2, 1, pad: EdgeInsets.fromLTRB(4.0, 12.0, 4.0, 4.0), align: Alignment.centerRight, child: _t('£5.00', sz: 12.0, color: Color(0xFF1A1C21), align: TextAlign.right)),
          cell(0, 1, 1, 2, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 0.0), child: _t('VAT in items (0%) (1)', sz: 12.0, bold: true, color: Color(0xFF1A1C21))),
          cell(1, 1, 2, 2, pad: EdgeInsets.symmetric(vertical: 12.0, horizontal: 0.0), align: Alignment.centerRight, child: _t('£5.00', sz: 12.0, color: Color(0xFF1A1C21), align: TextAlign.right)),
          Positioned(left: cs[0], top: rs[2], width: cs[1] - cs[0], height: rs[3] - rs[2], child: Container(
              decoration: BoxDecoration(color: Colors.transparent, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.fromLTRB(0.0, 12.0, 0.0, 30.0), alignment: Alignment.centerLeft, child: _t('Total Price (2)', sz: 12.0, bold: true, color: Color(0xFF1A1C21)))),
          Positioned(left: cs[1], top: rs[2], width: cs[2] - cs[1], height: rs[3] - rs[2], child: Container(
              decoration: BoxDecoration(color: Colors.transparent, border: Border(top: BorderSide(color: Color(0xFFD7DAE0), width: 1))),
              padding: EdgeInsets.fromLTRB(0.0, 12.0, 0.0, 30.0), alignment: Alignment.centerRight, child: _t('£5.00', sz: 12.0, bold: true, color: Color(0xFF1A1C21), align: TextAlign.right))),
          Positioned.fill(
            child: CustomPaint(
              painter: _TableGridPainter(
                colStarts: cs,
                rowStarts: rs,
                borderColor: Colors.black,
                borderWidth: 0.0,
                matrixData: matrixData,
                numRows: 3,
                numCols: 2,
              ),
            ),
          ),
        ],
      ),
    );
  },
))),
          cell(0, 4, 1, 5, pad: EdgeInsets.all(4.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('(1) VAT non applicable', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF1A1C21))),
                  Text('(2) Price includes the remuneration for MealShift Services', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF1A1C21))),
                ],
              )),
          Positioned.fill(
            child: CustomPaint(
              painter: _TableGridPainter(
                colStarts: cs,
                rowStarts: rs,
                borderColor: Colors.black,
                borderWidth: 0.0,
                matrixData: matrixData,
                numRows: 5,
                numCols: 4,
              ),
            ),
          ),
        ],
      ),
    );
  },
)),
          Positioned.fill(
            child: CustomPaint(
              painter: _TableGridPainter(
                colStarts: cs,
                rowStarts: rs,
                borderColor: Color(0xFFD7DAE0),
                borderWidth: 0.0,
                matrixData: matrixData,
                numRows: 3,
                numCols: 3,
              ),
            ),
          ),
        ],
      ),
    );
  },
),
)),
          cell(0, 2, 1, 3, pad: EdgeInsets.fromLTRB(4.0, 30.0, 4.0, 4.0), child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text('MealShift Ltd1 Assam Street, London - E1 7QLRegistration number:12793366', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0)),
                  Text('Any questions, contact customer service at support@mealshift.co.uk.', style: TextStyle(fontFamily: 'Browallia New', fontSize: 12.0, color: Color(0xFF1A1C21))),
                ],
              )),
          Positioned.fill(
            child: CustomPaint(
              painter: _TableGridPainter(
                colStarts: cs,
                rowStarts: rs,
                borderColor: Colors.black,
                borderWidth: 0.0,
                matrixData: matrixData,
                numRows: 3,
                numCols: 1,
              ),
            ),
          ),
        ],
      ),
    );
  },
),
),
),
            ),
          ),
        ),
        ),
      ),
    );
  }

  void _zoom(double delta) {
    setState(() {
      _currentScale = (_currentScale + delta).clamp(0.5, 5.0);
      _transformationController.value = Matrix4.diagonal3Values(_currentScale, _currentScale, 1.0);
    });
  }

  void _resetZoom() {
    setState(() {
      _currentScale = 1.0;
      _transformationController.value = Matrix4.identity();
    });
  }
}

// ============ HELPER CLASSES ============
// ── Text helpers ──────────────────────────────────────────────────────────────

Widget _t(String s, {double sz = 16, bool bold = false, Color? color, String ff = 'Browallia New', TextAlign? align}) =>
    Text(s, style: TextStyle(fontFamily: ff, fontSize: sz, fontWeight: bold ? FontWeight.bold : FontWeight.normal, color: color), softWrap: true, overflow: TextOverflow.clip, textAlign: align);

Widget _rt(List<(String, bool)> spans, {double sz = 16, String ff = 'Browallia New', TextAlign align = TextAlign.start}) =>
    RichText(softWrap: true, overflow: TextOverflow.clip, textAlign: align,
        text: TextSpan(style: TextStyle(fontFamily: ff, fontSize: sz),
            children: [for (final (t, b) in spans) TextSpan(text: t, style: b ? const TextStyle(fontWeight: FontWeight.bold) : null)]));

// ── Border helpers ────────────────────────────────────────────────────────────

const _bk = Colors.black;

class _TableGridPainter extends CustomPainter {
  final List<double> colStarts;
  final List<double> rowStarts;
  final Color borderColor;
  final double borderWidth;
  final List<List<int>> matrixData;
  final int numRows;
  final int numCols;

  const _TableGridPainter({
    required this.colStarts,
    required this.rowStarts,
    required this.borderColor,
    required this.borderWidth,
    required this.matrixData,
    required this.numRows,
    required this.numCols,
  });

  @override
  void paint(Canvas canvas, Size size) {
    if (borderWidth == 0) return;
    final paint = Paint()
      ..color = borderColor
      ..strokeWidth = borderWidth
      ..style = PaintingStyle.stroke;
    for (int r = 0; r < numRows; r++) {
      for (int c = 0; c < numCols; c++) {
        if (c >= colStarts.length - 1 || r >= rowStarts.length - 1) continue;
        final idx = (r < matrixData.length && c < matrixData[r].length)
            ? matrixData[r][c]
            : -1;
        if (idx < 0) continue;
        final sameAsLeft  = c > 0 && matrixData[r][c - 1] == idx;
        final sameAsAbove = r > 0 && matrixData[r - 1][c] == idx;
        if (sameAsLeft || sameAsAbove) continue;
        int endC = c + 1;
        while (endC < numCols && endC < matrixData[r].length && matrixData[r][endC] == idx) endC++;
        int endR = r + 1;
        while (endR < numRows && endR < matrixData.length && matrixData[endR][c] == idx) endR++;
        final right  = endC < colStarts.length ? colStarts[endC] : colStarts.last;
        final bottom = endR < rowStarts.length ? rowStarts[endR] : rowStarts.last;
        canvas.drawRect(Rect.fromLTRB(colStarts[c], rowStarts[r], right, bottom), paint);
      }
    }
  }

  @override
  bool shouldRepaint(_TableGridPainter old) =>
      old.borderColor != borderColor || old.borderWidth != borderWidth;
}